### ISSUE TITLE
Breakdown of meta community model

### ISSUE THREAD

**Issue by TanyaS08** [PoisotLab/Omnomnomivores#4]
As requested a breakdown of the model and its terms

**Comment by TanyaS08** [comment]
<img width="550" alt="Screenshot 2023-05-18 at 16 22 59" src="https://github.com/PoisotLab/Omnomnomivores/assets/61696728/db6f80b9-3735-4e54-9df0-cb7b420a52df">

This is the overall model. 

Xij(t) - abundance of species _i_ in patch _j_ at time _t_
Ci = rate of increase = 0.05
Bik = Interaction strength between species _i_ and _k_
Xkj(t) = abundance of species _k_ in patch _j_ at time _t_
Aij(t) = effect of environment on species _i_ in patch _j_ at time _t_ (will be expanded later)
Iij(t) = the number of individuals of species _i_ immigrating into patch _j_ at time _t_
ai = proportion of species _i_ that immigrates

**Comment by TanyaS08** [comment]
<img width="278" alt="Screenshot 2023-05-18 at 16 23 02" src="https://github.com/PoisotLab/Omnomnomivores/assets/61696728/b2281c2b-2f55-40d7-b10d-5c759cf4d661">

This is the environmental effect term.

h = scaling parameter = 300
Ej(t) = Environmental value in patch _j_ at time _t_
Hi = Environmental optimum for species _i_
\sigma = 50

**Comment by TanyaS08** [comment]
<img width="236" alt="Screenshot 2023-05-18 at 16 23 05" src="https://github.com/PoisotLab/Omnomnomivores/assets/61696728/66042505-d6c8-4f3b-9dca-c2553e261f90">

This is the immigration term.

ai = proportion of species _i_ that immigrates
Xil(t) = abundance of species _i_ in patch _l_ at time _t_
L = Strength of exponential decrease in dispersal distance (dispersal decay in script)
djl = distance between patch _j_ and _l_ (non zero probability that this is throwing things)

**Comment by TanyaS08** [comment]
Some other parameters/points of interest:

- S = number of species (80 in Thompson)
- M = number of environmental patches (200 in Thomson - linear though)
- Initial abundance for all species = 10
- Max distance = 200 (dropping this because maybe the magnitude of the distance is throwing out the immigration numbers??)
- Environment values ranged from 1 - 80 (again maybe a scaling thing but doubt it)
- Thompson also varied mean dispersal rate (ai) from 0.001 to 0.5 but we have fixed it to 0.25

**Comment by TanyaS08** [comment]
![Boundaries_model](https://github.com/PoisotLab/Omnomnomivores/assets/61696728/698d8f57-9d9d-4799-b54d-a222efd91099)

I'm only throwing this in here since it better breaks down how some of the sub components e.g. interaction strength is determined

**Comment by tpoisot** [comment]
https://github.com/PoisotLab/Omnomnomivores/blob/2c66195259b188890ccf83589b772cf6f059513b/01_code.jl#L270

This is such a beautiful bug

**Comment by tpoisot** [comment]
> <img width="278" alt="Screenshot 2023-05-18 at 16 23 02" src="https://github.com/PoisotLab/Omnomnomivores/assets/61696728/b2281c2b-2f55-40d7-b10d-5c759cf4d661">
> 
> This is the environmental effect term.
> 
> h = scaling parameter = 300
> Ej(t) = Environmental value in patch _j_ at time _t_
> Hi = Environmental optimum for species _i_
> \sigma = 50

The more I think about it, the more I think this part of the paper has a typo? Because when the species is at its optimum, the exponential is equal to 1, and so we have A = h-h = 0 -- this can't be right?

I'm also trying to parse the original `R` code.
