### ISSUE TITLE
Unused inputs for `_environmental_effect`

### ISSUE THREAD

**Issue by TanyaS08** [PoisotLab/Omnomnomivores#7]
Below is the _environmental_effect function:

```
function _environmental_effect(
    metacommunity,
    species,
    patch,
    generation,
    landscape::Matrix{Float64},
    environmental_optimum::Vector{Float64};
    h = 1.0,
    σ = 50.0,
)
    Δ = landscape[patch...] - environmental_optimum[species]
    ξ = 2σ^2.0
    modifier = exp(-(Δ^2.0) / (ξ))
    return h * modifier - h
end
```

Is there a reason we need to call/input metacommunity and generation? As far as I can tell we don't use them in the function so it seems unneeded?

**Comment by tpoisot** [comment]
There is a reason, and you're very welcome to say it's a bad one (and I kind of agree) -- when I re-organized the functions, I gave all of them the same signature, for two-ish reasons:

- no need to think about what goes in, always the same arguments in the same order
- if we have to change the content of the functions, the arguments are already there
- (this is the -ish) it's cheap to pass the memory address of an array

I get that it's a little confusing and makes the language server complain, so if you want to revert this to make sure there are no warnings about unused arguments, it's fine with me.

**Comment by TanyaS08** [comment]
It was a actually for a fourth secret reason that I opened the issue, which was that when I was trying to dig into the environmental effect it just felt weird. Vibes were shaky but not off.
